export const ADMIN_STRINGS = {
  polyclinics: {
    title: "Manajemen Master Poliklinik",
    subtitle: "Kelola entitas poliklinik dan integrasikan layanan dengan Vector DB Chatbot.",
    addBtn: "Tambah Poliklinik Baru",
    tableHeaderName: "Nama Poliklinik",
    tableHeaderDesc: "Deskripsi",
    tableHeaderStatus: "Status Layanan",
    tableHeaderActions: "Aksi",
    statusActive: "Aktif",
    statusInactive: "Non-Aktif",
    editTitle: "Ubah Poliklinik",
    addTitle: "Tambah Poliklinik",
    nameLabel: "Nama Poliklinik",
    namePlaceholder: "Contoh: Poli Jantung & Pembuluh Darah",
    descLabel: "Deskripsi Poliklinik",
    descPlaceholder: "Contoh: Layanan spesialis untuk diagnosis dan pengobatan penyakit jantung.",
    imgLabel: "Tautan Gambar / Icon",
    activeLabel: "Status Aktif",
    saveBtn: "Simpan Data",
    cancelBtn: "Batal",
    deleteConfirm: "Apakah Anda yakin ingin menghapus poliklinik ini?",
    successCreate: "Poliklinik berhasil ditambahkan.",
    successUpdate: "Poliklinik berhasil diperbarui.",
    errorFetch: "Gagal memuat data poliklinik.",
    errorCreate: "Gagal menambahkan poliklinik.",
    errorUpdate: "Gagal memperbarui poliklinik.",
    errorDelete: "Gagal menghapus poliklinik.",
    successDelete: "Poliklinik berhasil dihapus.",
  },
  doctors: {
    title: "Manajemen Master Dokter",
    subtitle: "Kelola data dokter, spesialisasi, dan data kontak untuk asisten AI.",
    addBtn: "Tambah Dokter Baru",
    tableHeaderName: "Nama Dokter",
    tableHeaderSpec: "Spesialisasi",
    tableHeaderContact: "Info Kontak",
    tableHeaderStatus: "Status Praktik",
    tableHeaderActions: "Aksi",
    statusActive: "Praktik",
    statusInactive: "Cuti",
    editTitle: "Ubah Data Dokter",
    addTitle: "Tambah Dokter Baru",
    nameLabel: "Nama Lengkap Dokter",
    namePlaceholder: "Contoh: dr. Budi Santoso, Sp.J",
    specPlaceholder: "Contoh: Spesialis Jantung",
    contactPlaceholder: "Contoh: 08123456789",
    descPlaceholder: "Contoh: Berpengalaman 10 tahun di bidang kardiologi...",
    specLabel: "Spesialisasi",
    contactLabel: "Email / Kontak",
    descLabel: "Biografi Singkat",
    imgLabel: "Tautan Foto",
    activeLabel: "Status Aktif Praktik",
    saveBtn: "Simpan Data",
    cancelBtn: "Batal",
    deleteConfirm: "Apakah Anda yakin ingin menghapus data dokter ini?",
    successCreate: "Data dokter berhasil ditambahkan.",
    successUpdate: "Data dokter berhasil diperbarui.",
    successDelete: "Data dokter berhasil dihapus.",
  },
  schedules: {
    title: "Jadwal Praktik",
    addBtn: "Tambah Jadwal Baru",
    dateLabel: "Tanggal",
    datePlaceholder: "Contoh: 2023-12-31",
    startPlaceholder: "Contoh: 08:00",
    endPlaceholder: "Contoh: 12:00",
    quotaPlaceholder: "Contoh: 20",
    startLabel: "Jam Mulai",
    endLabel: "Jam Selesai",
    quotaLabel: "Kuota Pasien",
    saveBtn: "Simpan Jadwal",
    successCreate: "Jadwal berhasil ditambahkan.",
    successDelete: "Jadwal berhasil dihapus.",
    deleteConfirm: "Hapus jadwal ini?",
  },
  scheduleCalendar: {
    noSchedule: "Tidak ada jadwal dokter pada tanggal ini.",
    available: "Tersedia",
    full: "Penuh",
    quotaAvailable: "Tersedia",
    quotaFilled: "Terisi",
    defaultDoctor: "Dokter Spesialis",
    defaultSpecialization: "Spesialis Umum",
    schedulePrefix: "Jadwal Tanggal",
  },
  appointments: {
    title: "Antrean Pasien",
    subtitle: "Pantau jadwal dan janji temu pasien (Live Booking Queue).",
    cancelConfirmTitle: "Batalkan Antrean",
    cancelConfirmDesc: "Apakah Anda yakin ingin membatalkan antrean pasien ini? Aksi ini tidak dapat dikembalikan.",
    cancelConfirmBtn: "Ya, Batalkan",
    msgApprove: "Antrean berhasil disetujui",
    msgCancel: "Antrean dibatalkan",
    msgComplete: "Antrean diselesaikan",
  },
  branches: {
    title: "Manajemen Cabang RS",
    subtitle: "Kelola lokasi cabang rumah sakit, koordinat peta, dan tautan Rute Google Maps.",
    addBtn: "Tambah Cabang Baru",
    tableHeaderName: "Nama Cabang",
    tableHeaderAddress: "Alamat Lengkap",
    tableHeaderGmaps: "Google Maps Link",
    tableHeaderActions: "Aksi",
    editTitle: "Ubah Data Cabang",
    addTitle: "Tambah Cabang Baru",
    nameLabel: "Nama Rumah Sakit",
    namePlaceholder: "Contoh: Cabang Jakarta Pusat",
    addressPlaceholder: "Contoh: Jl. Jend. Sudirman Kav. 21, Jakarta Selatan",
    latPlaceholder: "Contoh: -6.2088",
    lngPlaceholder: "Contoh: 106.8456",
    gmapsPlaceholder: "Contoh: https://maps.app.goo.gl/abcd123",
    addressLabel: "Alamat",
    latLabel: "Latitude",
    lngLabel: "Longitude",
    gmapsLabel: "Tautan Google Maps",
    imgLabel: "Tautan Foto",
    saveBtn: "Simpan Data",
    cancelBtn: "Batal",
    deleteConfirm: "Apakah Anda yakin ingin menghapus data cabang ini?",
    successCreate: "Cabang RS berhasil ditambahkan.",
    successUpdate: "Cabang RS berhasil diperbarui.",
    successDelete: "Cabang RS berhasil dihapus.",
  },
  users: {
    title: "Manajemen Pengguna",
    subtitle: "Kelola akses RBAC (Admin, Dokter, Apoteker, Pasien)",
    addBtn: "Tambah Pengguna",
    passEditPlaceholder: "Biarkan kosong jika tidak diubah",
    passNewPlaceholder: "Minimal 6 karakter",
    namePlaceholder: "Contoh: Budi Santoso",
    emailPlaceholder: "Contoh: budi@herminahospitals.com",
    phonePlaceholder: "Contoh: 08123456789",
  },
} as const;
