export const COMMON_STRINGS = {
  common: {
    medicalResultsUpdated: "Hasil medis diperbarui",
    medicalResultsAdded: "Hasil medis berhasil ditambahkan",
    medicalResultsLoadFailed: "Gagal memuat hasil medis",
    medicalResultsSaveFailed: "Gagal menyimpan data",
    searchStatus: "Pilih Status",
    searchSchedule: "Pilih Jadwal",
    searchSort: "Atur Urutan",
    searchFilter: "Terapkan Filter",
    searchPolyclinic: "Pilih Poliklinik",
    searchType: "Pilih Jenis",
    searchPatient: "Pencarian Nama, Email, atau No HP Pasien",
    uploadExternal: "Atau tempel URL eksternal (Opsional)",
    phonePlaceholder: "812-3456-7890",
    loadError: "Gagal memuat data",
    updateSuccess: "Berhasil memperbarui data",
    createSuccess: "Berhasil menambahkan data",
    saveError: "Gagal menyimpan data",
    deleteSuccess: "Berhasil menghapus data",
    deleteError: "Gagal menghapus data",
    clinicalOnly: "Aksi klinis hanya untuk Dokter/Apoteker",
    action: "Aksi",
    cancel: "Batal",
    save: "Simpan",
    imageUploadSuccess: "Gambar berhasil diunggah",
    imageUploadError: "Terjadi kesalahan jaringan saat mengunggah",
    fileUploadSuccess: "Berkas berhasil diunggah",
    fileUploadError: "Terjadi kesalahan jaringan saat mengunggah",
    promoSaveSuccess: "Berhasil menyimpan promo",
    userUpdateSuccess: "Pengguna diperbarui",
    userCreateSuccess: "Pengguna ditambahkan",
    userLoadError: "Gagal memuat data pengguna",
    userDeleteSuccess: "Pengguna berhasil dihapus",
    categoryAddSuccess: "Kategori berhasil ditambahkan",
    categoryAddError: "Gagal menambahkan kategori",
    validationMissingFields: "User ID, Nama Tes, dan Tanggal wajib diisi",
    validationReminderFields: "Pilih pasien, isi Judul, dan lengkapi Tanggal beserta Waktu (Jam).",
    reminderLoadError: "Gagal memuat data reminder",
    reminderSendSuccess: "Reminder berhasil dikirim ke pasien",
    reminderCreateError: "Gagal membuat reminder",
    reminderDeleteSuccess: "Reminder dihapus",
    reminderDeleteError: "Gagal menghapus reminder",
    ragStatusError: "Gagal mengambil status RAG Engine",
    ragHistoryError: "Gagal memuat histori chat",
    ragSyncSuccess: "Sinkronisasi berhasil! Knowledge Base telah diperbarui.",
    ragSyncError: "Gagal melakukan sinkronisasi: ",
    loginPatientError: "Akses ditolak: Pasien tidak memiliki izin masuk ke portal Admin.",
    prescribeSuccess: "E-Resep berhasil diterbitkan!",
    prescribeError: "Gagal menerbitkan E-Resep",
  },
  errors: {
    UNAUTHENTICATED: "Email atau kata sandi salah.",
    UNAUTHORIZED: "Anda tidak memiliki hak akses sebagai admin.",
    VALIDATION_ERROR: "Validasi data gagal. Periksa input Anda.",
    INTERNAL_ERROR: "Terjadi kesalahan internal server.",
  },
  details: {
    viewDetails: "Lihat Detail",
    userTitle: "Detail Pengguna",
    promoTitle: "Detail Promo",
    medicineTitle: "Detail Obat",
    email: "Email",
    phone: "Telepon",
    dob: "Tanggal Lahir",
    gender: "Jenis Kelamin",
    bloodType: "Golongan Darah",
    heightWeight: "Tinggi / Berat",
    allergies: "Alergi",
    noAllergies: "Tidak ada riwayat alergi",
    registeredAt: "Terdaftar Sejak",
    promoTitleLabel: "Judul Promo",
    promoSubtitle: "Sub-judul",
    promoTheme: "Warna Tema",
    status: "Status",
    statusActiveRun: "Aktif (Sedang Berjalan)",
    statusInactive: "Tidak Aktif",
    createdAt: "Dibuat Pada",
    addedAt: "Ditambahkan Pada",
    category: "Kategori",
    dosageUnit: "Dosis / Satuan",
    price: "Harga (Rp)",
    currentStock: "Stok Saat Ini",
  },
  validation: {
    nameEmpty: "Nama lengkap wajib diisi.",
    nameInvalid: "Nama hanya boleh mengandung huruf, spasi, titik, atau tanda petik (tanpa angka).",
    emailEmpty: "Email wajib diisi.",
    emailInvalid: "Format email tidak valid (contoh: nama@gmail.com).",
    emailDomainInvalid: "Gunakan provider email resmi (Gmail, Yahoo, Outlook, iCloud, atau email institusi).",
    emailTypoDetected: "Domain email terdeteksi salah ketik. Periksa kembali akhiran email Anda.",
    phoneEmpty: "Nomor telepon wajib diisi.",
    phoneInvalid: "Nomor HP harus berupa angka Indonesia valid (diawali 08, 628, atau +628) dengan panjang 10-14 digit.",
    phoneShort: "Nomor HP terlalu pendek.",
    phoneLong: "Nomor HP terlalu panjang.",
    passwordEmpty: "Kata sandi wajib diisi.",
    passwordWeak: "Kata sandi minimal 8 karakter dengan kombinasi huruf besar, huruf kecil, dan angka.",
    requiredSuffix: " tidak boleh kosong.",
    quotaEmpty: "Kuota pasien tidak boleh kosong.",
    quotaMin: "Minimal pasien/kuota adalah 10.",
  },
} as const;
