import { THEME_RAW_COLORS } from "./theme_colors";

export const FEATURE_STRINGS = {
  promos: {
    addPromo: "Tambah Promo Baru",
    editPromo: "Ubah Promo",
    title: "Judul Promo",
    titlePlaceholder: "Contoh: Paket Persalinan",
    subtitle: "Deskripsi / Subtitle",
    subtitlePlaceholder: "Contoh: Diskon 20%",
    themeColor: "Warna Tema (Hex)",
    defaultColor: THEME_RAW_COLORS.dark.primary,
    statusActive: "Status Aktif",
    active: "Aktif",
    searchPlaceholder: "Pencarian Promo",
    pageTitle: "Manajemen Promo",
    pageSubtitle: "Atur promo dan penawaran spesial untuk aplikasi pasien",
  },
  login: {
    title: "Hermina Admin Portal",
    subtitle: "Silakan masuk ke control center Hermina Smart Assistant.",
    emailLabel: "Alamat Email",
    emailPlaceholder: "nama@herminahospitals.com",
    passwordLabel: "Kata Sandi",
    passwordPlaceholder: "••••••••",
    submitButton: "Masuk ke Dashboard",
    submittingButton: "Sedang Memproses",
    invalidEmailError: "Format email tidak valid.",
    emptyFieldsError: "Email dan kata sandi wajib diisi.",
    networkError: "Gagal terhubung ke server backend.",
    successMessage: "Login berhasil! Mengalihkan ke dashboard...",
  },
  sidebar: {
    title: "Hermina Admin",
    dashboard: "Dashboard",
    polyclinics: "Master Poliklinik",
    doctors: "Master Dokter",
    aiAudit: "AI Audit History",
    logout: "Keluar",
  },
  dashboard: {
    title: "Overview Control Center",
    welcome: "Selamat datang kembali, ",
    cardDoctors: "Total Dokter Terdaftar",
    cardPolyclinics: "Total Poliklinik",
    cardSchedules: "Jadwal Aktif Hari Ini",
    descDoctors: "Dokter terintegrasi dengan SIRS",
    descPolyclinics: "Layanan poliklinik aktif",
    descSchedules: "Sesi praktik dokter aktif",
  },
  aiOrchestrator: {
    title: "AI Orchestrator Dashboard",
    subtitle: "Pantau status Vector Database dan sinkronisasi data RAG.",
    knowledgeBaseSize: "Knowledge Base Size",
    knowledgeBaseDesc: "Total teks ter-embedding di FAISS Vector DB",
    manualSyncBtn: "Mulai Sinkronisasi Manual",
    manualSyncSubmitting: "Sinkronisasi Berjalan",
    syncSuccess: "Sinkronisasi Vector DB selesai!",
    syncError: "Gagal menyelaraskan database vektor.",
  },
  medicalResults: {
    pageTitle: "Hasil Medis Pasien",
    pageSubtitle: "Input dan kelola hasil lab, radiologi, dan pemeriksaan medis lainnya.",
    addBtn: "Tambah Hasil Medis",
    patientIdPlaceholder: "Contoh: 10234",
    doctorNamePlaceholder: "Contoh: dr. Budi Santoso, Sp.PD",
    testTypePlaceholder: "Contoh: Darah Lengkap",
    datePlaceholder: "Contoh: 2023-12-31",
    resultPlaceholder: "Contoh: Kadar hemoglobin normal...",
    notesPlaceholder: "Contoh: Perbanyak minum air putih...",
    fileUrlPlaceholder: "Contoh: https://herminahospitals.com/hasil.pdf",
  },
  reminders: {
    pageTitle: "Pengingat Pasien",
    pageSubtitle: "Kirim notifikasi / pengingat ke pasien terdaftar.",
    addBtn: "Kirim Reminder Baru",
    titlePlaceholder: "Contoh: Jadwal Kontrol Rutin",
    datePlaceholder: "Contoh: 2023-12-31T10:00",
    messagePlaceholder: "Contoh: Halo Bapak/Ibu, ini adalah pengingat...",
    formTitle: "Form Kirim Reminder",
    patientLabel: "Pasien *",
    patientSelect: "— Pilih Pasien —",
    typeLabel: "Tipe Reminder",
    titleLabel: "Judul *",
    dateLabel: "Tanggal & Waktu *",
    messageLabel: "Pesan",
    submitButton: "Kirim Reminder",
  },
  pharmacy: {
    addMedicine: "Tambah Obat",
    editMedicine: "Edit Obat",
    medicineName: "Nama Obat",
    category: "Kategori",
    price: "Harga",
    stock: "Stok",
    prescription: "Resep",
    requiresPrescription: "Wajib Resep",
    otc: "Bebas",
    medicinePhoto: "Foto Obat",
    loadError: "Gagal memuat resep",
    processSuccess: "Resep berhasil ditebus ke pesanan",
    processError: "Gagal memproses resep",
  },
  pharmacists: {
    title: "Manajemen Apoteker",
    subtitle: "Kelola akun apoteker, data lisensi/kontak, dan operasional farmasi.",
    addBtn: "Tambah Apoteker Baru",
    editTitle: "Ubah Data Apoteker",
    addTitle: "Tambah Apoteker Baru",
    nameLabel: "Nama Lengkap & Gelar",
    namePlaceholder: "Contoh: Fahmi Prisma, S.Farm, Apt.",
    emailLabel: "Email Akun",
    emailPlaceholder: "apoteker@herminahospitals.com",
    phoneLabel: "Nomor WhatsApp / Telepon",
    passwordLabel: "Kata Sandi",
    passwordPlaceholder: "Minimal 8 karakter (huruf besar, kecil, angka)",
    passwordEditNote: "Kosongkan jika tidak ingin mengubah kata sandi.",
    activeStatus: "Status Akun Aktif",
    deleteConfirm: "Hapus Apoteker",
    deleteMessage: "Apakah Anda yakin ingin menghapus akun apoteker ini?",
    successCreate: "Apoteker berhasil ditambahkan.",
    successUpdate: "Data apoteker berhasil diperbarui.",
    successDelete: "Apoteker berhasil dihapus.",
    empty: "Belum ada data apoteker.",
  },
} as const;
