export type ThemeMode = "light" | "dark";

export const THEME_RAW_COLORS = {
  light: {
    background: "#f8fafc",
    foreground: "#0f172a",
    primary: "#113c2b",
    primaryHover: "#1e5e44",
    primaryForeground: "#FAFAFA",
    surfacePrimary: "#FAFAFA",
    surfaceSecondary: "#f1f5f9",
    overlayLight: "rgba(255, 255, 255, 0.95)",
    overlayDark: "rgba(0, 0, 0, 0.05)",
    glassBg: "rgba(255, 255, 255, 0.7)",
    glassBorder: "rgba(17, 60, 43, 0.08)",
    glassShadow: "0 8px 32px 0 rgba(0, 0, 0, 0.08)",
    cardBg: "rgba(255, 255, 255, 0.85)",
    cardBorder: "rgba(17, 60, 43, 0.1)",
    inputBg: "rgba(255, 255, 255, 0.95)",
    inputBorder: "rgba(17, 60, 43, 0.15)",
  },
  dark: {
    background: "#091a13",
    foreground: "#f1f5f9",
    primary: "#1e5e44",
    primaryHover: "#2d825f",
    primaryForeground: "#FAFAFA",
    surfacePrimary: "#091a13",
    surfaceSecondary: "#0f2b1f",
    overlayLight: "rgba(9, 26, 19, 0.95)",
    overlayDark: "rgba(255, 255, 255, 0.05)",
    glassBg: "rgba(9, 26, 19, 0.8)",
    glassBorder: "rgba(255, 255, 255, 0.08)",
    glassShadow: "0 8px 32px 0 rgba(0, 0, 0, 0.3)",
    cardBg: "rgba(17, 60, 43, 0.45)",
    cardBorder: "rgba(30, 94, 68, 0.45)",
    inputBg: "rgba(9, 26, 19, 0.65)",
    inputBorder: "rgba(30, 94, 68, 0.55)",
  },
  semantic: {
    success: "#10b981",
    successForeground: "#FAFAFA",
    successMuted: "rgba(16, 185, 129, 0.1)",
    successHover: "rgba(16, 185, 129, 0.2)",
    error: "#f43f5e",
    errorForeground: "#FAFAFA",
    errorMuted: "rgba(244, 63, 94, 0.1)",
    errorHover: "rgba(244, 63, 94, 0.2)",
    warning: "#f59e0b",
    warningForeground: "#FAFAFA",
    warningMuted: "rgba(245, 158, 11, 0.1)",
    warningHover: "rgba(245, 158, 11, 0.2)",
    info: "#3b82f6",
    infoForeground: "#FAFAFA",
    infoMuted: "rgba(59, 130, 246, 0.1)",
    infoHover: "rgba(59, 130, 246, 0.2)",
    neutral: "#64748b",
    neutralMuted: "rgba(100, 116, 139, 0.1)",
    accent: "#a855f7",
    accentForeground: "#FAFAFA",
    accentMuted: "rgba(168, 85, 247, 0.1)",
    teal: "#14b8a6",
    tealForeground: "#FAFAFA",
    tealMuted: "rgba(20, 184, 166, 0.1)",
    darkPanel: "rgba(26, 26, 26, 0.7)",
  },
} as const;

export const CSS_VARS = {
  darkPanel: "var(--color-dark-panel)",
  background: "var(--background)",
  foreground: "var(--foreground)",
  primary: "var(--primary)",
  primaryHover: "var(--primary-hover)",
  primaryForeground: "var(--primary-foreground)",
  success: "var(--success)",
  successForeground: "var(--success-foreground)",
  successMuted: "var(--success-muted)",
  successHover: "var(--success-hover)",
  error: "var(--error)",
  errorForeground: "var(--error-foreground)",
  errorMuted: "var(--error-muted)",
  errorHover: "var(--error-hover)",
  warning: "var(--warning)",
  warningForeground: "var(--warning-foreground)",
  warningMuted: "var(--warning-muted)",
  warningHover: "var(--warning-hover)",
  info: "var(--info)",
  infoForeground: "var(--info-foreground)",
  infoMuted: "var(--info-muted)",
  infoHover: "var(--info-hover)",
  neutral: "var(--neutral)",
  neutralMuted: "var(--neutral-muted)",
  accent: "var(--accent)",
  accentForeground: "var(--accent-foreground)",
  accentMuted: "var(--accent-muted)",
  teal: "var(--teal)",
  tealForeground: "var(--teal-foreground)",
  tealMuted: "var(--teal-muted)",
  surfacePrimary: "var(--surface-primary)",
  surfaceSecondary: "var(--surface-secondary)",
  overlayLight: "var(--overlay-light)",
  overlayDark: "var(--overlay-dark)",
  glassBg: "var(--glass-bg)",
  glassBorder: "var(--glass-border)",
  glassShadow: "var(--glass-shadow)",
  cardBg: "var(--card-bg)",
  cardBorder: "var(--card-border)",
  inputBg: "var(--input-bg)",
  inputBorder: "var(--input-border)",
  fontSans: "var(--font-geist-sans)",
  fontMono: "var(--font-geist-mono)",
} as const;
