export const APP_STRINGS = {
  login: {
    title: "Hermina Admin Portal",
    subtitle: "Silakan masuk ke control center Hermina Smart Assistant.",
    emailLabel: "Alamat Email",
    emailPlaceholder: "nama@herminahospitals.com",
    passwordLabel: "Kata Sandi",
    passwordPlaceholder: "••••••••",
    submitButton: "Masuk ke Dashboard",
    submittingButton: "Memproses...",
    invalidEmailError: "Format email tidak valid.",
    emptyFieldsError: "Email dan kata sandi wajib diisi.",
    networkError: "Gagal terhubung ke server backend.",
    successMessage: "Login berhasil! Mengalihkan ke dashboard...",
  },
  sidebar: {
    title: "Hermina Admin",
    dashboard: "Dashboard",
    polyclinics: "Master Poliklinik",
    doctors: "Master Dokter",
    aiAudit: "AI Audit History",
    logout: "Keluar",
  },
  dashboard: {
    title: "Overview Control Center",
    welcome: "Selamat datang kembali, ",
    cardDoctors: "Total Dokter Terdaftar",
    cardPolyclinics: "Total Poliklinik",
    cardSchedules: "Jadwal Aktif Hari Ini",
    descDoctors: "Dokter terintegrasi dengan SIRS",
    descPolyclinics: "Layanan poliklinik aktif",
    descSchedules: "Sesi praktik dokter aktif",
  },
  polyclinics: {
    title: "Manajemen Master Poliklinik",
    subtitle: "Kelola entitas poliklinik dan integrasikan layanan dengan Vector DB Chatbot.",
    addBtn: "Tambah Poliklinik Baru",
    tableHeaderName: "Nama Poliklinik",
    tableHeaderDesc: "Deskripsi",
    tableHeaderStatus: "Status Layanan",
    tableHeaderActions: "Aksi",
    statusActive: "Aktif",
    statusInactive: "Non-Aktif",
    editTitle: "Ubah Poliklinik",
    addTitle: "Tambah Poliklinik",
    nameLabel: "Nama Poliklinik",
    descLabel: "Deskripsi Poliklinik",
    imgLabel: "Tautan Gambar / Icon",
    activeLabel: "Status Aktif",
    saveBtn: "Simpan Data",
    cancelBtn: "Batal",
    deleteConfirm: "Apakah Anda yakin ingin menghapus poliklinik ini?",
    successCreate: "Poliklinik berhasil ditambahkan.",
    successUpdate: "Poliklinik berhasil diperbarui.",
    successDelete: "Poliklinik berhasil dihapus.",
  },
  doctors: {
    title: "Manajemen Master Dokter",
    subtitle: "Kelola data dokter, spesialisasi, dan data kontak untuk asisten AI.",
    addBtn: "Tambah Dokter Baru",
    tableHeaderName: "Nama Dokter",
    tableHeaderSpec: "Spesialisasi",
    tableHeaderContact: "Info Kontak",
    tableHeaderStatus: "Status Praktik",
    tableHeaderActions: "Aksi",
    statusActive: "Praktik",
    statusInactive: "Cuti",
    editTitle: "Ubah Data Dokter",
    addTitle: "Tambah Dokter Baru",
    nameLabel: "Nama Lengkap Dokter",
    specLabel: "Spesialisasi",
    contactLabel: "Email / Kontak",
    descLabel: "Biografi Singkat",
    imgLabel: "Tautan Foto",
    activeLabel: "Status Aktif Praktik",
    saveBtn: "Simpan Data",
    cancelBtn: "Batal",
    deleteConfirm: "Apakah Anda yakin ingin menghapus data dokter ini?",
    successCreate: "Data dokter berhasil ditambahkan.",
    successUpdate: "Data dokter berhasil diperbarui.",
    successDelete: "Data dokter berhasil dihapus.",
  },
  schedules: {
    title: "Jadwal Praktik",
    addBtn: "Tambah Jadwal Baru",
    dateLabel: "Tanggal",
    startLabel: "Jam Mulai",
    endLabel: "Jam Selesai",
    quotaLabel: "Kuota Pasien",
    saveBtn: "Simpan Jadwal",
    successCreate: "Jadwal berhasil ditambahkan.",
    successDelete: "Jadwal berhasil dihapus.",
    deleteConfirm: "Hapus jadwal ini?",
  },
  branches: {
    title: "Manajemen Cabang RS",
    subtitle: "Kelola lokasi cabang rumah sakit, koordinat peta, dan tautan Rute Google Maps.",
    addBtn: "Tambah Cabang Baru",
    tableHeaderName: "Nama Cabang",
    tableHeaderAddress: "Alamat Lengkap",
    tableHeaderGmaps: "Google Maps Link",
    tableHeaderActions: "Aksi",
    editTitle: "Ubah Data Cabang",
    addTitle: "Tambah Cabang Baru",
    nameLabel: "Nama Rumah Sakit",
    addressLabel: "Alamat",
    latLabel: "Latitude",
    lngLabel: "Longitude",
    gmapsLabel: "Tautan Google Maps",
    imgLabel: "Tautan Foto",
    saveBtn: "Simpan Data",
    cancelBtn: "Batal",
    deleteConfirm: "Apakah Anda yakin ingin menghapus data cabang ini?",
    successCreate: "Cabang RS berhasil ditambahkan.",
    successUpdate: "Cabang RS berhasil diperbarui.",
    successDelete: "Cabang RS berhasil dihapus.",
  },
  aiOrchestrator: {
    title: "AI Orchestrator Dashboard",
    subtitle: "Pantau status Vector Database dan sinkronisasi data RAG.",
    knowledgeBaseSize: "Knowledge Base Size",
    knowledgeBaseDesc: "Total teks ter-embedding di FAISS Vector DB",
    manualSyncBtn: "Mulai Sinkronisasi Manual",
    manualSyncSubmitting: "Sinkronisasi berjalan...",
    syncSuccess: "Sinkronisasi Vector DB selesai!",
    syncError: "Gagal menyelaraskan database vektor.",
  },
  errors: {
    UNAUTHENTICATED: "Email atau kata sandi salah.",
    UNAUTHORIZED: "Anda tidak memiliki hak akses sebagai admin.",
    VALIDATION_ERROR: "Validasi data gagal. Periksa input Anda.",
    INTERNAL_ERROR: "Terjadi kesalahan internal server.",
  },
} as const;
